### ISSUE TITLE
Multiple groups do not work

### ISSUE THREAD

**Issue by TheChaosToast** [RLNT/sinus-header-groups#10]
Hello everybody,

I'm desperate with the Groups 2.0.0 script header. I have created several groups on the test server:

Testing               (this is my header group)
_________            (should also be part of the header group)
Test - Gaming    (trigger group)
Bot testing         (trigger group)

If I assign bot / test gaming to the user, the testing header group is also assigned. But the ________ is not added in any way. I went through all possible scenarios to add the underscore (for better clarity) - unfortunately without success.

best regards

**Comment by DAmNRelentless** [comment]
I think you are using the wrong script for your idea. You should try our other script where you are able to assign multiple groups at once. Check it out [here](https://forum.sinusbot.com/resources/rlnt-automated-server-groups.419/)!
The Header Groups script is indeed just for assigning a single group.
